# Generated by Django 5.1.3 on 2024-11-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldData', models.TextField(verbose_name='Исходные данные')),
                ('sortData', models.TextField(verbose_name='Отсортированные данные')),
            ],
        ),
    ]
